### ISSUE TITLE
[products] The products header link is missing a left border

### ISSUE THREAD

**Issue by anthonydillon** [ubuntudesign/www.canonical.com#16]
Looks like we do not want to be setting the border-left to 0 instead:

```css
.banner .nav-primary ul li a.active, 
.banner .nav-primary ul li a:link.active, 
.banner .nav-primary ul li a:visited.active {
  background-color: #591f3e;
  /* border-left: 0; */
}
```
